image: python:3.8

build:
  script:
    - pip install -r requirements-dev.txt
    - flake8
    - coverage run
    - coverage report
    - coverage xml
  artifacts:
    reports:
      junit: coverage.xml
